DEFAULT_BEACON_INTERVAL = 15  # SEND DATA EVERY 15 SEC
DEFAULT_LOCK_STATE = True  # States if box is locked initially
INITIAL_GPS = [0.0000, 0.0000]  # Initial GPS location where the box should be
GPS_THRESHOLD = 16  # The distance beyond which the box going is considered unsafe
URL = "https://io.adafruit.com/api/v2/"  # Adafruit default URL
USER_NAME = "XXXXXXXXXXXXXXX"  # username of the user
FEED_SEND = "xxxxxxx"  # esp sending feed
API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # api key
FEED_RECEIVE = "XXXXX"  # esp receiving feed
VIBRATION_FREQUENCY = 6 #random vibration frequency
