# Generated by Django 3.1.4 on 2021-05-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazewarriorsorders',
            name='orderId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppHome.amazeusersorders'),
        ),
    ]
