# Generated by Django 3.1.4 on 2021-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0002_auto_20210529_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazeusersorders',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
    ]
