# Generated by Django 3.1.4 on 2021-05-29 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0003_amazeusersorders_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazeusersorders',
            name='orderDate',
            field=models.DateField(default=datetime.date(1997, 10, 19)),
        ),
    ]
